### ISSUE TITLE
Solve competitive programming questions in any programming language

### ISSUE THREAD

**Issue by sidanand67** [sidanand67/Competitive-Programming#1]
Hello coders,
Here is a chance for all to contribute to this repo by solving the questions given in the [sheet](https://docs.google.com/spreadsheets/d/1iJZWP2nS_OB3kCTjq8L6TrJJ4o-5lhxDOyTaocSYc-k/edit#gid=84654839).
More details regarding the same are given in the Readme.md file. 
Make sure you follow the rules mentioned in the Contributing.md file.
If you have any queries, you can reply to this thread. 

Good Luck!

**Comment by ghsayan** [comment]
Can I add few solutions for B category ?

**Comment by sidanand67** [comment]
Yes, you can.

**Comment by robin07** [comment]
Can i add solutions to few questions mentioned in the sheet directly, without opening it as new issue?

**Comment by sidanand67** [comment]
Yes, you can add directly.

**Comment by deepanshuoct12** [comment]
I would like to work on this in. Can you please assign it to me?

**Comment by VIPUL662** [comment]
hello sir i would like to add a algorithm to find longest substring without repeating characters

**Comment by VIPUL662** [comment]
please assign me
