### ISSUE TITLE
Choosing a Laptop

### ISSUE THREAD

**Issue by MananOO12** [sidanand67/Competitive-Programming#105]
Problem link
 [Click Here](http://codeforces.com/problemset/problem/106/B)

Folder Location
B -> Choosing a laptop -> UserName.extension

Languages

 

- [ ] C
- [x]  C++
- [ ] Python
- [ ] Java
- [ ] Javascript

**Comment by MananOO12** [comment]
Can I do this one as well?

**Comment by sidanand67** [comment]
Submissions are not accepted for this issue.
