### ISSUE TITLE
Burning Midnight Oil

### ISSUE THREAD

**Issue by MananOO12** [sidanand67/Competitive-Programming#107]
Problem Link
[Click Here](http://codeforces.com/problemset/problem/165/B)

Folder Location
B ->Burning Midnight Oil -> UserName.extension

Languages

- [ ] C
- [ ]  C++
- [x]  Python
- [ ] Java
- [ ] Javascript

**Comment by MananOO12** [comment]
I can do this in python.

**Comment by MananOO12** [comment]
#108 
Completed the problem in python

**Comment by PrakashAditya17** [comment]
I can code in java.

**Comment by MananOO12** [comment]
> I can code in java.

Go ahead and link this issue to your pull request.
Also ask the owner to assign it to you.

**Comment by PrakashAditya17** [comment]
Alright. Do I have to ask the owner separately or he would assign on his own to me?

**Comment by MananOO12** [comment]
> Alright. Do I have to ask the owner separately or he would assign on his own to me?

Mention him using @

**Comment by PrakashAditya17** [comment]
@sidanand67 I can code it in java, do assign if required. Thanks for the help @MananOO12 , may I know if this would count for the hacktoberfest if I get pull request?

**Comment by MananOO12** [comment]
> @sidanand67 I can code it in java, do assign if required. Thanks for the help @MananOO12 , may I know if this would count for the hacktoberfest if I get pull request?

Yes it will when your pull request is accepted.

**Comment by PrakashAditya17** [comment]
Thanks for the information.

**Comment by sidanand67** [comment]
Submissions are not accepted for this issue.
