### ISSUE TITLE
Wrong Subtraction

### ISSUE THREAD

**Issue by immortal-j** [sidanand67/Competitive-Programming#109]
Problem [click here](https://codeforces.com/problemset/problem/977/A)

Folder Location
A ->Wrong Subtraction -> UserName.extension

Languages

 

- [ ] C
- [x] C++
- [ ]  Python
- [ ] Java
- [ ] Javascript

**Comment by aniket173000** [comment]
Hi, could you assign this issue to me , I have solved this problem I am ready with my complete solution code.

**Comment by immortal-j** [comment]
> Hi, could you assign this issue to me , I have solved this problem I am ready with my complete solution code.

Can you please tell me the language you have used

**Comment by aniket173000** [comment]
I have used C++.

**Comment by immortal-j** [comment]
#117 
Solutions in other languages are required

**Comment by DragonBaronDev** [comment]
I can solve it using java

**Comment by immortal-j** [comment]
> I can solve it using java

Yes go ahead and link your pull request to this issue and ask the owner to assign it to you

**Comment by immortal-j** [comment]
@sidanand67  
Can I Create pull requests directly without creating issues because i have solutions ready for more than 40 problems.

**Comment by sidanand67** [comment]
Submissions are not accepted for this issue.

**Comment by kritika2311** [comment]
I have commit the solution of this issue before it is closed but you ask me for some changes so I have done the changes and commit it back today. Please consider my solution for this issue.
