### ISSUE TITLE
Minimum Product 

### ISSUE THREAD

**Issue by Kabirdutt** [sidanand67/Competitive-Programming#110]
Problem Link
[Click here](https://codeforces.com/contest/1409/problem/B)

Folder Location
B ->Minimum Product -> UserName.extension

Languages

- [ ]  C
- [x]  C++
- [ ]  Python
- [ ] Java
- [ ]  Javascript

**Comment by aniket173000** [comment]
HI can you please assign this issue to me I am ready with my solution code.

**Comment by Kabirdutt** [comment]
in which language

**Comment by aniket173000** [comment]
I have done it using c++ .

**Comment by Kabirdutt** [comment]
> I have done it using c++ .

If you have solution in any other language then I can assign you this issue

**Comment by aniket173000** [comment]
I can do it using python .

**Comment by Kabirdutt** [comment]
#119 I have solved this question using C++ , you can submit this question using any other language.

**Comment by GarvitBanga** [comment]
Can you assign me for Java

**Comment by PrakashAditya17** [comment]
I had participated in that contest and have my solution in java. Do assign if required.

**Comment by sidanand67** [comment]
Submissions are not accepted for this issue.
