### ISSUE TITLE
Teams Forming 

### ISSUE THREAD

**Issue by Kabirdutt** [sidanand67/Competitive-Programming#120]
Problem Link
[Click here](https://codeforces.com/gym/284355/problem/A)

Folder Location
A->Teams_Forming -> UserName.extension

Languages

- [ ]  C
- [x] C++
- [ ]  Python
- [ ] Java
- [ ] Javascript

Note: Assignment is not required for opening PR.

**Comment by Kabirdutt** [comment]
#119  This is the solution to Team Forming.

**Comment by Kabirdutt** [comment]
Can we create the pull request direct without creating an issue. 
Because I have solved more than 80 questions and every time creating an issue would be more  hectic. @sidanand67

**Comment by sidanand67** [comment]
You can directly submit your PR only for those questions that are listed in sheet. Other questions are not accepted. 
You can even add your favorite algorithms in newly created algorithms folder.
