### ISSUE TITLE
Beautiful Matrix 

### ISSUE THREAD

**Issue by Kabirdutt** [sidanand67/Competitive-Programming#151]
Problem Link
[Click Here](codeforces.com/contest/263/problem/A)

Folder Location
A->Beautiful Matrix -> UserName.extension

Languages

- [ ]  C
- [x]  C++
- [ ] Python
- [ ]  Java
- [ ] Javascript

**Comment by Kabirdutt** [comment]
This is Solution to Beautiful Matrix.

**Comment by darkcocoa** [comment]
I want to try this problem out in cpp/Java (whichever is preferred by you). Please assign this to me.

**Comment by Kabirdutt** [comment]
> I want to try this problem out in cpp/Java (whichever is preferred by you). Please assign this to me.

ask the owner to merge this and add the solution in java
