### ISSUE TITLE
Beautiful Matrix

### ISSUE THREAD

**Issue by sidanand67** [sidanand67/Competitive-Programming#17]
**Problem Link**
[Click Here](http://codeforces.com/contest/263/problem/A)

**Folder Location** (create folder if it doesn't exist)
A -> Problem_Name -> UserName.extension

**Languages**

- [x] C 

- [x] C++

- [x] Python

- [ ] Javascript

- [ ] Java

**Comment by aswarth123** [comment]
I would like to do it in c++ and python can you assign it to me.

**Comment by Jayasree77** [comment]
I like to work on this in javascript @sidanand67

**Comment by Spolutrean** [comment]
Hello, I would like to solve this problem on java, can you please assign in for me?
