### ISSUE TITLE
Vanya and Fence

### ISSUE THREAD

**Issue by sidanand67** [sidanand67/Competitive-Programming#2]
**Problem Link**
[Click Here](http://codeforces.com/contest/677/problem/A)

**Folder Location** (create folder if it doesn't exist)
A -> Vanya_and_Fence -> UserName.extension

**Languages**

- [x] C 

- [x] C++

- [ ] Python

- [ ] Javascript

- [ ] Java

**Comment by ghsayan** [comment]
Can I work on this ?

**Comment by sidanand67** [comment]
sure

**Comment by Exter-dg** [comment]
Can you assign this to me for C?

**Comment by Abhijeet-sonkar** [comment]
Can I solve this problem in Java?

**Comment by Jayasree77** [comment]
Can I solve this in python? @sidanand67

**Comment by Rudransh24** [comment]
Hello! Can you assign this problem to me in Python?
