### ISSUE TITLE
Added JumpGame in C++

### ISSUE THREAD

**Issue by Starkultra** [sidanand67/Competitive-Programming#234]
Problem Link

Algorithm->JumpGame->your_username.cpp

Languages

- [ ] C

- [x] C++

- [ ] Python

- [ ] Javascript

- [ ] Java

**Comment by Starkultra** [comment]
Will you please assign this issue??

**Comment by sidanand67** [comment]
You can upload your algorithm in the appropriate folder. Just make sure you add comments explaining the problem statement.
