### ISSUE TITLE
Gravity Flip

### ISSUE THREAD

**Issue by sidanand67** [sidanand67/Competitive-Programming#24]
**Problem Link**
[Click Here](http://codeforces.com/contest/405/problem/A)

**Folder Location** (create folder if it doesn't exist)
A -> Problem_Name -> Username.extension

**Languages**

- [ ] C 

- [x] C++

- [ ] Python

- [ ] Javascript

- [ ] Java

**Comment by ikjot-2605** [comment]
@sidanand67 can I claim this?

**Comment by ikjot-2605** [comment]
@sidanand67 Do I need to code this in all languages?
Or is just one okay?

**Comment by AnjaliBhuva** [comment]
I have done this in python,can u plz assign it to me?

**Comment by Rudransh24** [comment]
Hello! Can you please assign this problem to me in C, or python?

**Comment by Spolutrean** [comment]
Hello, I would like to solve this problem on java, can you please assign in for me?

**Comment by AxeL-7** [comment]
Hello! Can you please assign this problem to me in python?
