### ISSUE TITLE
Petya and Strings

### ISSUE THREAD

**Issue by sidanand67** [sidanand67/Competitive-Programming#25]
**Problem Link**
[Click Here](http://codeforces.com/contest/112/problem/A)

**Folder Location** (create folder if it doesn't exist)
A -> Problem_Name -> Username.extension

**Languages**

- [ ] C 

- [x] C++

- [x] Python

- [ ] Javascript

- [ ] Java

**Comment by shivangigoel1302** [comment]
hey can you assign this to me! i would like to solve this in C++

**Comment by donno2048** [comment]
I can solve this using python, can you assign me?

**Comment by robin07** [comment]
can i work on this in c++? because c++ code in repo is giving WA on codeforces.

**Comment by sidanand67** [comment]
Thanks @robin07 for pointing out the mistake. You can work on it.

**Comment by Jayasree77** [comment]
I can solve this using javascript, can you assign it to me?

**Comment by rgarg-2711** [comment]
can you please assign it to me?

**Comment by Rudransh24** [comment]
Can you please assign this problem to me in C?
