### ISSUE TITLE
Petya and Countryside

### ISSUE THREAD

**Issue by sidanand67** [sidanand67/Competitive-Programming#26]
**Problem Link**
[Click Here](http://codeforces.com/contest/66/problem/B)

**Folder Location** (create folder if it doesn't exist)
B -> Problem_Name -> Username.extension

**Languages**

- [ ] C 

- [x] C++

- [x] Python

- [ ] Javascript

- [ ] Java

**Comment by donno2048** [comment]
I can solve this using python, can you assign me?

**Comment by donno2048** [comment]
Actually, I think there are problems with the examples on the site...

**Comment by donno2048** [comment]
I submitted #37 but it's not working according to the examples because they're wrong.

**Comment by sidanand67** [comment]
Thanks for contributing. I'll check it and see what's wrong.

**Comment by sidanand67** [comment]
> I submitted #37 but it's not working according to the examples because they're wrong.

I've checked out the examples. They are correct. 
There's something wrong in your code.

**Comment by donno2048** [comment]
Oh, I thought I need to print the number of the section... Oops, should be an easy fix

**Comment by sidanand67** [comment]
Yes, I have merged your PR.

**Comment by MananOO12** [comment]
I had done this one in C++
Can you assign it to me?

**Comment by MananOO12** [comment]
I've added the solution in C++ can you check it please?

**Comment by aniket173000** [comment]
Hi could you please assign me this problem to solve in c++ .
