### ISSUE TITLE
Caisa and Pylons

### ISSUE THREAD

**Issue by sidanand67** [sidanand67/Competitive-Programming#27]
**Problem Link**
[Click Here](http://codeforces.com/contest/463/problem/B)

**Folder Location** (create folder if it doesn't exist)
B -> Problem_Name -> UserName.extension

**Languages**

- [ ] C 

- [x] C++

- [ ] Python

- [ ] Javascript

- [ ] Java

**Comment by ikjot-2605** [comment]
Can I claim this @sidanand67 ?

**Comment by shrutikdev** [comment]
Can I contribute to this for python?

**Comment by Spolutrean** [comment]
Hello, I would like to solve this problem on java, can you please assign in for me?
