### ISSUE TITLE
Bear and Finding Criminals

### ISSUE THREAD

**Issue by sidanand67** [sidanand67/Competitive-Programming#28]
**Problem Link**
[Click Here](http://codeforces.com/contest/680/problem/B)

**Folder Location** (create folder if it doesn't exist)
B -> Problem_Name -> UserName.extension

**Languages**

- [ ] C 

- [x] C++

- [ ] Python

- [ ] Javascript

- [x] Java

**Comment by robin07** [comment]
can i work on this in c++?

**Comment by Deimantas95** [comment]
Hey! 
I can solve this in Java.
