### ISSUE TITLE
Burglar and Matches

### ISSUE THREAD

**Issue by sidanand67** [sidanand67/Competitive-Programming#29]
**Problem Link**
[Click Here](http://codeforces.com/contest/16/problem/B)

**Folder Location** (create folder if it doesn't exist)
B -> Problem_Name -> UserName.extension

**Languages**

- [ ] C 

- [x] C++

- [x] Python

- [ ] Javascript

- [ ] Java

**Comment by donno2048** [comment]
I can solve this using python, can you assign me?

**Comment by MananOO12** [comment]
> **Problem Link**
> [Click Here](http://codeforces.com/contest/16/problem/B)
> 
> **Folder Location** (create folder if it doesn't exist)
> B -> Problem_Name -> UserName.extension
> 
> **Languages**
> 
> * [ ]  C
> * [x]  C++
> * [x]  Python
> * [ ]  Javascript
> * [ ]  Java

Can you assign this to me I can do this in C++?

**Comment by rgarg-2711** [comment]
can you please assign it to me?

**Comment by GarvitBanga** [comment]
Assign for Javascript
