### ISSUE TITLE
Anton and Danik

### ISSUE THREAD

**Issue by sidanand67** [sidanand67/Competitive-Programming#3]
**Problem Link**
[Click Here](http://codeforces.com/contest/734/problem/A)

**Folder Location** (create folder if it doesn't exist)
A -> Anton_and_Danik -> UserName.extension

**Languages**

- [x] C 

- [x] C++

- [x] Python

- [ ] Javascript

- [ ] Java

**Comment by Exter-dg** [comment]
I would like to work on this in C++. Can you assign it to me?

**Comment by sidanand67** [comment]
sure

**Comment by khushi2912** [comment]
I would love to work on this in C. Can you please assign this to me?

**Comment by donno2048** [comment]
I can solve this using python, can you assign me?

**Comment by Spolutrean** [comment]
Hello, I would like to solve this problem on java, can you please assign in for me?
