### ISSUE TITLE
Boy or Girl

### ISSUE THREAD

**Issue by sidanand67** [sidanand67/Competitive-Programming#39]
**Problem Link**
[Click Here](http://codeforces.com/contest/236/problem/A)

**Folder Location** (create folder if it doesn't exist)
A -> Boy_or_Girl -> UserName.extension

**Languages**

- [ ] C 

- [x] C++

- [x] Python

- [x] Javascript

- [x] Java

**Comment by Gurvir-Sandhar** [comment]
Can I take this issue? I would like to use javascript.

**Comment by robin07** [comment]
can i work on this in c++?

**Comment by rgarg-2711** [comment]
can you please assign it to me?

**Comment by Rudransh24** [comment]
Can you assign this problem to me in C?
@sidanand67
