### ISSUE TITLE
Watermelon_4A

### ISSUE THREAD

**Issue by BhuvaneshPatil** [sidanand67/Competitive-Programming#4]

**Comment by sidanand67** [comment]
Hello, 
If you are opening an issue then kindly use the following format. This format ensures that contributors get everything at one place.
Thanks.

**Problem Link**
[Click Here](Link)

**Folder Location** (create folder if it doesn't exist)
A -> Problem_Name -> FileName.extension

**Languages**

- [ ] C 

- [ ] C++

- [ ] Python

- [ ] Javascript

- [ ] Go

- [ ] Java

- [ ] Php

- [ ] C#
