### ISSUE TITLE
Word

### ISSUE THREAD

**Issue by sidanand67** [sidanand67/Competitive-Programming#40]
**Problem Link**
[Click Here](http://codeforces.com/contest/59/problem/A)

**Folder Location** (create folder if it doesn't exist)
A -> Word -> UserName.extension

**Languages**

- [ ] C 

- [x] C++

- [x] Python

- [ ] Javascript

- [ ] Java

**Comment by MayankAg20** [comment]
Could you please assign this to me? I am willing to do this.

**Comment by AnjaliBhuva** [comment]
can I write the program in python?

**Comment by Divyessh** [comment]
I have made the program for python. Can I contribute?

**Comment by Divyessh** [comment]
#49  I have made a PR

**Comment by Rudransh24** [comment]
Can you please assign this problem to me in C?

**Comment by Hutcheeran** [comment]
Hi could please you assign me this problem in Java?
