### ISSUE TITLE
Magnets

### ISSUE THREAD

**Issue by sidanand67** [sidanand67/Competitive-Programming#41]
**Problem Link**
[Click Here](http://codeforces.com/contest/344/problem/A)

**Folder Location** (create folder if it doesn't exist)
A -> Magnets -> UserName.extension

**Languages**

- [ ] C 

- [x] C++

- [x] Python

- [ ] Javascript

- [ ] Java

**Comment by Tripathi-Vaibhav** [comment]
Do I have to write the program in all mentioned languages in your issue or any one of my choice ?
Also should I have to add comments ?

**Comment by sidanand67** [comment]
You can code in any language. There's no obligation to code in all the languages. 
You can either comment your code or use appropriate variable and function names.

**Comment by Tripathi-Vaibhav** [comment]
Ok then,  I am working on it.
I'll send pull request soon.

**Comment by MayankAg20** [comment]
could I be assigned too? I'll finish it quickly

**Comment by shrutikdev** [comment]
,

**Comment by shrutikdev** [comment]
can you assign this to me for python?

**Comment by GarvitBanga** [comment]
Can you assign me for Javascript?

**Comment by Rudransh24** [comment]
Can you please assign this problem to me in C??
