### ISSUE TITLE
Bear and Big Brother

### ISSUE THREAD

**Issue by sidanand67** [sidanand67/Competitive-Programming#5]
**Problem Link**
[Click Here](http://codeforces.com/contest/791/problem/A)

**Folder Location** (create folder if it doesn't exist)
A -> Bear_and_Big_Brother -> UserName.extension

**Languages**

- [x] C 

- [x] C++

- [x] Python

- [ ] Javascript

- [ ] Java

**Comment by pranjanpr** [comment]
@sidanand67  I can do this in C++. Is it fine ?

**Comment by Abhijeet-sonkar** [comment]
Can I solve this  problem in python?

**Comment by ednardorubens** [comment]
Can I solve this problem in Java?

**Comment by shrutikdev** [comment]
Can you assign this to me for python?

**Comment by rgarg-2711** [comment]
can you please assign it to me?
