### ISSUE TITLE
Sereja and Dima

### ISSUE THREAD

**Issue by sidanand67** [sidanand67/Competitive-Programming#54]
**Problem Link**
[Click Here](http://codeforces.com/contest/381/problem/A)

**Folder Location** (create folder if it doesn't exist)
A -> Sereja_and_Dima -> UserName.extension

**Languages**

- [ ] C 

- [x] C++

- [ ] Python

- [ ] Javascript

- [x] Java

**Comment by Harshal0506** [comment]
I would be more than happy to try my hand on this in c++
assign it to me @shadyonfire

**Comment by omarr45** [comment]
I solved this problem a few days ago and I have its code ready
could you assign me on it?

**Comment by omarr45** [comment]
@sidanand67 
Great! please check the pull request

Thank you

**Comment by Rohanfizz** [comment]
Do i have to solve the problem in all The languages mentioned? I dont know javascript :(

**Comment by Itachi8374** [comment]
I have solved this problem in C++ before. @sidanand67 can you assign this issue to me, i will be happy to work on it

**Comment by Rohanfizz** [comment]
Please check the Pull request ivve solved it in C, CPP , JAVA, all codes are symmetrical to each other, same variable names and easy to understand.
Peace :)

**Comment by Kunal2007** [comment]
I am willing to solve it in C, C++ or Python. Please assign it to me.

**Comment by sidanand67** [comment]
@Kunal2007 You can do it in python.

**Comment by GarvitBanga** [comment]
Can you please assign me for javascript?

**Comment by Rudransh24** [comment]
Can you please assign this problem to me in C or python?

**Comment by Chidu2000** [comment]
assign me a problem in c++ , I would love solving it

**Comment by vansh-8502** [comment]
can u assign me for java pls

**Comment by sidanand67** [comment]
You can directly add your codes for the above problem without assignment.
