### ISSUE TITLE
Stones on the table

### ISSUE THREAD

**Issue by sidanand67** [sidanand67/Competitive-Programming#55]
**Problem Link**
[Click Here](http://codeforces.com/contest/266/problem/A)

**Folder Location** (create folder if it doesn't exist)
A -> Stones_on_the_Table -> UserName.extension

**Languages**

- [ ] C 

- [x] C++

- [ ] Python

- [ ] Javascript

- [x] Java

**Comment by deepanshuoct12** [comment]
I would like to work on this in C++. Can you please assign it to me?

**Comment by Harshal0506** [comment]
assign me in c 
I will try to do it as soon as possible
any time limit from your side?
@deepanshuoct12 
Thanks for providing such a oppourtunity

**Comment by sidanand67** [comment]
There is no time limit. You can take your time to solve it.

**Comment by sidanand67** [comment]
I'll push everyone's code.

**Comment by Kunal2007** [comment]
Can I also do it in C++?

**Comment by FazeelUsmani** [comment]
Please do assign me to do in Python and C++

**Comment by Arsenic-ATG** [comment]
do I have to be assigned to before posting the code ?
I have [done it in C++](https://codeforces.com/contest/266/submission/94887033) and is waiting for you to assign me to this issue in order for me to create a pull request.

**Comment by sidanand67** [comment]
@FazeelUsmani You can do it in python.

**Comment by meteora2002** [comment]
Hey there!
I would like to contribute using python 
language. Kindly assign me some work. Thank you!Hey there!

**Comment by aniket173000** [comment]
Hi , I would like to contribute using C++.
Please assign me this work.

**Comment by Rudransh24** [comment]
Hello! Can you please assign me this problem in C.

**Comment by TheAnshul756** [comment]
Hello! Can you please assign me this problem in C, C++ or Java.

**Comment by Hutcheeran** [comment]
Hiya! Can you please me assign the problem to me in Java? :)

**Comment by sidanand67** [comment]
You can directly add your code for the problem without assignment.

**Comment by manthan2501** [comment]
I would like to work on this problem in C++/C. Please assign me.
