### ISSUE TITLE
Sum of digits

### ISSUE THREAD

**Issue by sidanand67** [sidanand67/Competitive-Programming#56]
**Problem Link**
[Click Here](http://codeforces.com/contest/102/problem/B)

**Folder Location** (create folder if it doesn't exist)
B -> Sum_of_Digits -> UserName.extension

**Languages**

- [x] C 

- [x] C++

- [x] Python

- [ ] Javascript

- [ ] Java

**Comment by PranavMurali** [comment]
the problem link is currently offline, could you describe the problem instead?

**Comment by sidanand67** [comment]
I wish, I remembered the problem. 
We need to wait for codeforces to get back online.

**Comment by deepanshuoct12** [comment]
can  I resolve the issue?

**Comment by sidanand67** [comment]
@deepanshuoct12 yeah sure.

**Comment by sidanand67** [comment]
But i think codeforces is still not active 🤔

**Comment by foxxmg** [comment]
codeforces is still down damn.

**Comment by psymbio** [comment]
if it ever comes back up, do notify.

**Comment by omarr45** [comment]
Can I work on this for C++?
I have the problem and can submit its solution
@sidanand67

**Comment by Itachi8374** [comment]
Can I work on this problem in C++ @sidanand67

**Comment by Jayasree77** [comment]
Can I work on this problem in python? @sidanand67

**Comment by Kunal2007** [comment]
I want to code it in C++. Please assign it to me.

**Comment by DragonBaronDev** [comment]
I can solve it using java. Can you assign it to me?

**Comment by neha07kumari** [comment]
Can i solve it in C or python ? @sidanand67

**Comment by sidanand67** [comment]
You can directly add your code for the problem without assignment.
