### ISSUE TITLE
Team

### ISSUE THREAD

**Issue by sidanand67** [sidanand67/Competitive-Programming#57]
**Problem Link**
[Click Here](http://codeforces.com/contest/231/problem/A)

**Folder Location** (create folder if it doesn't exist)
A -> Team -> UserName.extension

**Languages**

- [ ] C 

- [x] C++

- [x] Python

- [ ] Javascript

- [ ] Java

**Comment by uchiha-7** [comment]
Can you assign this issue to me? I will solve it in C++.
Thanks

**Comment by sidanand67** [comment]
@uchiha-7 are you able to access the problem link?

**Comment by uchiha-7** [comment]
Not right now. I will do it as soon as codeforces is available.
Thanks

**Comment by sidanand67** [comment]
Thanks for the info.

**Comment by Harshal0506** [comment]
Can you assign it to me in c
@sidanand67 I am unable to see the question currently but I will try my best 
thanks

**Comment by rsrahul1000** [comment]
Hi @sidanand67 , I had solved this problem before for practice purpose, please assign it to me
Thanks in Anticipation :)

**Comment by utkarsh48** [comment]
I want to do it in python or JS. please Assign me.

**Comment by Itachi8374** [comment]
i want to solve this problem in C++,  @sidanand67 please assign it to me

**Comment by Rohanfizz** [comment]
Hey can u please assign this to me? I will solve it in JAVA
Peace :)

**Comment by Vojsmaname** [comment]
I want to do this problem in Java. @sidanand67  Can you assign it to me?

**Comment by SaurabhVj** [comment]
I can solve it in C @sidanand67 , Can you assign it to me ?

**Comment by DragonBaronDev** [comment]
I can solve it for java @sidanand67. Can you assing it to me?

**Comment by Rudransh24** [comment]
Can you please assign this problem to me in C?

**Comment by SaurabhVj** [comment]
@Rudransh24 I have already claimed this issue in C. Please look into other issues.

**Comment by AStream26** [comment]
@sidanand67 can you please  assign this to me in c++?

**Comment by duttabhishek32** [comment]
Hey there, I can write the code in C. Can you assign this to me for **C** ?

**Comment by kritika2311** [comment]
Hey, can I write the code for the solution of problem in python?
