### ISSUE TITLE
Follow this format to raise issues for problems listed in the sheet

### ISSUE THREAD

**Issue by sidanand67** [sidanand67/Competitive-Programming#6]
**Problem Link**
[Click Here](Link)

**Folder Location** (create folder if it doesn't exist)
A -> Problem_Name -> UserName.extension

**Languages**

- [ ] C 

- [ ] C++

- [ ] Python

- [ ] Javascript

- [ ] Java

Note: Assignment is not required for opening PR.

_You are all requested to follow the above format to raise issues._
_Issue title should be problem name_
_Also add appropriate labels to this issue_
_Thankyou_

**Comment by rgarg-2711** [comment]
Can you please assign it to me?
